rm(list=ls())
library("mlogit")
library("survival")
library("fastDummies")
setwd("~/Desktop/mpak")
dataset <- read.csv("clogitchoice_data.csv")
attach(dataset)
table(Fuel)
table(Make)
table(Fuel.size.segment)
dataset <- dummy_cols(dataset, select_columns = 'Fuel')
cond = clogit(Fuel_El ~ Cost.km..DKK.+Horsepower+strata(Year),data=dataset)
summary(cond)


