rm(list=ls())
library("mlogit")
setwd("~/Desktop/mpak")
dataset <- read.csv("final_data.csv")
attach(dataset)
table(Fuel)
table(Make)
table(Fuel.size.segment)
table(Yearold)
Yearold <-2022 - Year
logi <- glm(El ~ Yearold + Weight..kg.+Prices..2015.DKK.+Engine.effect..kW.+Cost.km..DKK., family = binomial(link = "logit"), data = dataset)
summary(logi)
